### ISSUE TITLE
cant add account

### ISSUE THREAD

**Issue by bimantt** [Poojan38380/Instagram-Scraper-Manager#1]
Failed to check for existing username: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66ff2070085a367047721d78, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

**Comment by Poojan38380** [comment]
That is because you need to add your MONGO DB uri in your environment variables.
